version: 2
updates:
- package-ecosystem: nuget
  directory: "/csharp-selenium-webdriver-sample"
  schedule:
    interval: daily
    time: "08:30"  # UTC
- package-ecosystem: npm
  directory: "/typescript-selenium-webdriver-sample"
  schedule:
    interval: daily
    time: "08:30"  # UTC
  versioning-strategy: increase
  ignore:
    # Major version of @types/node is pinned to match the version of node we
    # use for builds (ideally, latest LTS)
  - dependency-name: "@types/node"
    versions:
    - ">=17.0.0"
- package-ecosystem: npm
  directory: "/typescript-playwright-sample"
  schedule:
    interval: daily
    time: "08:30"  # UTC
  versioning-strategy: increase
  ignore:
    # Major version of @types/node is pinned to match the version of node we
    # use for builds (ideally, latest LTS)
  - dependency-name: "@types/node"
    versions:
    - ">=17.0.0"
